### ISSUE TITLE
Echoregions functionality notebook

### ISSUE THREAD

**Issue by valentina-s** [OSOceanAcoustics/echoregions#10]
A notebook describing the different attributes and methods of the objects in echoregions (regions & lines). 
- [ ] UML diagram
- [ ] regions functionality
- [ ] lines functionality

Geared toward technical people who would want to modify it/extend it.

**Comment by leewujung** [comment]
Closing this issue since it has been captured in other issues. We will eventually need comprehensive documentation type notebooks.
