### ISSUE TITLE
Add EchoRegions to Package Repositories

### ISSUE THREAD

**Issue by ctuguinay** [OSOceanAcoustics/echoregions#116]
- [x] Prior to the first release of EchoRegions, it should be added to Zenodo (for the DOI)

After the first release of EchoRegions, it should be added to the following popular package repositories:

- [x] PyPi
- [ ] Conda

To help facilitate this addition of EchoRegions to the previously mentioned package repositories, one should follow the code detailed in Echopype.

**Comment by leewujung** [comment]
Also see #68 for reference. Feel free to close that one if everything is done/captured here.

**Comment by leewujung** [comment]
Seems like we just need to add this to conda. I'll move this to under v0.1.1 release.

**Comment by leewujung** [comment]
Since `echoregions` is now on pypi and zenodo, we can do without conda for now. I'll close this issue and open a new one for adding conda recipe.
