### ISSUE TITLE
Fix type checkings to `isinstance`

### ISSUE THREAD

**Issue by lsetiawan** [OSOceanAcoustics/echoregions#120]
## Overview

There are pieces of the code that does type comparison using `type(blah) == mytype`. This now seem to fail during [pre-commit.ci](https://results.pre-commit.ci/run/github/332865211/1690874886.24Qr5YbvS2axFRoDXxT7Xg) as seen in PR https://github.com/OSOceanAcoustics/echoregions/pull/119. The better solution when comparing type, use `isinstance(blah, mytype)`.

## Places with errors

https://github.com/OSOceanAcoustics/echoregions/blob/25a451851a17b131a9112b2bca850ba0340d4cea/echoregions/regions2d/regions2d.py#L413-L419

https://github.com/OSOceanAcoustics/echoregions/blob/25a451851a17b131a9112b2bca850ba0340d4cea/echoregions/tests/test_r2d.py#L32-L37

**Comment by ctuguinay** [comment]
Thanks for spotting this! @lsetiawan, will add this to my testing PR.
