### ISSUE TITLE
Allow `Regions2D` to be initialized with a CSV file

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echoregions#130]
Currently `Regions2D` objects are initialized with an EVR file. It would be useful to also allow a CSV as the input file, for the use case where we are moving things back and forth between concatenated dataframes and EVR and masks.

This should be fairly straightforward, but it'll take a bit of work to make sure the dataframe format is in good order by checking all required columns exist.

**Comment by ctuguinay** [comment]
Closed by #148
