### ISSUE TITLE
Use `**kwargs` to delegate interpolation method selection to `pandas.DataFrame.interpolate`

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echoregions#151]
Currently in `Lines.mask` the allowed interpolation schemes are hard-coded and also cannot accept the associated kwargs for `spline` and `krogh`. This can be circumvented by passing the `method` and the associated kwargs to `pandas.DataFrame.interpolate` so if anything fails it fails there.

**Comment by leewujung** [comment]
Also reading into the `Lines.mask` function some more, using `kwargs` will also allow passing additional arguments such as `limit_area`, `limit_direction`, etc to the `pandas.DataFrame.interpolate` function under the hood.

**Comment by ctuguinay** [comment]
Closed by #156
