### ISSUE TITLE
Region Masking Functionality

### ISSUE THREAD

**Issue by valentina-s** [OSOceanAcoustics/echoregions#42]
The `mask` function of the `Regions2D` object is not working currently. 

The actual functionality is in the `mask` method of the [`Regions2DMasker`](https://github.com/OSOceanAcoustics/echoregions/blob/main/echoregions/mask/region_mask.py)

Working example for making "Hake" region masks (only one region) in this [notebook](https://github.com/uw-echospace/hake-labels/blob/main/notebooks/convert_region_to_mask_all.ipynb).

Some considerations: 
* input could be one or many regions (based on region id's)
* user wants all regions for a given label to be in the same mask
* user want regions with different labels to be layers  in the mask dataset
* user wants regions with different labels to be in one layer (for example they want to combine all fish regions into one layer)
* provide some options to the user how to store the pixel values of the masked regions

A few extra details:

- [x] adding regionmask version as a requirement
- [x] adding __init__.py
- [x] add examples in notebooks
- [x] add examples selecting different regions based on labels

**Comment by leewujung** [comment]
#45 partially addressed this issue.

**Comment by valentina-s** [comment]
The only one that is not addressed is 3) storing different regions in different layers. I will make a stand alone issue and we can discuss the format. #75
