### ISSUE TITLE
Remove `frame.append` since it is being deprecated.

### ISSUE THREAD

**Issue by valentina-s** [OSOceanAcoustics/echoregions#46]
`evr_parser` is using `df.append` to append rows. Append to list and concat instead.

**Comment by leewujung** [comment]
@valentina-s : has this been fixed?

**Comment by ctuguinay** [comment]
I forgot to say during our last meeting, but frame.append is what is causing a lot of the errors mentioned in #79, making this issue redundant and of smaller scope than #79. I will make a PR to #79 soon and close this issue once that PR has been reviewed and merged.

**Comment by ctuguinay** [comment]
Resolved with #79
