### ISSUE TITLE
Determine Earliest Working Regionmask Version

### ISSUE THREAD

**Issue by valentina-s** [OSOceanAcoustics/echoregions#49]
* determine earliest `regionmask` working version
* Masking function does not work with 0.7.0 (one gets `unix_time` instead of `ping_time`; need to add tests to catch this error). 0.9.0 works.

**Comment by ctuguinay** [comment]
Renamed from "Add environment setup instructions for different systems" to "Determine Earliest Working Regionmask Version" to better match the above comments.
