### ISSUE TITLE
Review design `Region2D` and other related modules

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echoregions#54]
In reviewing #45 I had some [comments](https://github.com/OSOceanAcoustics/echoregions/pull/45#issuecomment-1339804565) on the current structure of `Region2D` and related modules.

That PR was merged so that we can move forward on the project, so this issue is a reminder that we should revisit these.

The comments are reproduced below:
* review the use case of `Region2D` to have clarity on whether we should just parse EVR file at init, or change the input to accept both EVR and CSV/JSON that were converted previously.
* `convert_points`:
  * currently lives in `evr_parser.py` but I think it should just live in `Region2D`
  * it is currently unused. From your comment above it seems that some more work is needed to smooth out the points.
* `get_points_from_region`: this function does not currently work since there is no `get_points_from_region` under `Regions2DPlotter`
* `Region2DPlotter`: when should it be initialized?
* add docstring for `Regions2DMasker.mask` (from `Region2D.mask`

**Comment by ctuguinay** [comment]
I am under the impression that all these points have been addressed in current/previous PRs and issues, so I will close this issue.
