### ISSUE TITLE
Update Shapely version to >=2.0.0 or unpin it

### ISSUE THREAD

**Issue by valentina-s** [OSOceanAcoustics/echoregions#56]
shapely dependency (which is a dependency of regionmask) is pinned to 1.8.2, since 2.0.0 version causes some issue (`ValueError: Inconsistent coordinate dimensionality`). regionmask==0.9.0 seems to require >1.7.0. Going forward the code should be adjusted to the later version, and possibly sort out backward compatibility.

**Comment by leewujung** [comment]
> Going forward the code should be adjusted to the later version

The "later version" here do you mean 2.0.0?

**Comment by leewujung** [comment]
Investigate if we can unpin shapely so that it works with both new and old versions.
