### ISSUE TITLE
Revamp testing suite with new converted file from echopype 0.7.1

### ISSUE THREAD

**Issue by valentina-s** [OSOceanAcoustics/echoregions#58]
- [ ] potentially use fixtures where possible
- [ ] ensure testing with raw files, nc, zarr files
- [ ] make sure only small testing files are in github

**Comment by ctuguinay** [comment]
Do we still want to test on raw and zarr files? I was under the impression we were going to only work with .nc files.

**Comment by ctuguinay** [comment]
This issue should be addressed in the same PR that addresses #107.

**Comment by valentina-s** [comment]
[Here](https://drive.google.com/drive/u/0/folders/1XKtwlPDD7tAVPswf4GwoUVaKItgSa9K9) is a link to a zip file with a more recently converted example from 2019 Survey. It also has a bottom if needed. It is a whole transect but it can be cut into pieces/and possibly further subsampled if needed. I am assuming you want to test with an example which already has depth and regular grid incorporated? But could provide also some more raw files in `.zarr` format which have not been yet combined.

**Comment by valentina-s** [comment]
> 

So the functions should be tested on an xarray (which may have come from `.zarr` or `.nc`), and for simplicity we can make the reading from `.nc`. I think the only difference that can come from the different formats is the way they are chunked, and whether they are loaded into RAM or not. I assume if they are not the `regionmask` function will invoke it? We have converted `.zarr` files handy, and I think opening them with `xarray` and converting them to `.nc` will be the same as converting them from scratch.

**Comment by valentina-s** [comment]
> Do we still want to test on raw and zarr files? I was under the impression we were going to only work with .nc files.

So the functions should be tested on an xarray (which may have come from .zarr or .nc), and for simplicity we can make the reading from .nc. I think the only difference that can come from the different formats is the way they are chunked, and whether they are loaded into RAM or not. I assume if they are not the regionmask function will invoke it? We have converted .zarr files handy, and I think opening them with xarray and converting them to .nc will be the same as converting them from scratch.
