### ISSUE TITLE
datetime encoding for older version of xarray and recent pandas breaking changes

### ISSUE THREAD

**Issue by valentina-s** [OSOceanAcoustics/echoregions#65]
During testing, `xarray==0.16.2` raises nanosecond encoding error: https://github.com/pydata/xarray/pull/4400

It seems it is resolved in `xarray==2023.2.0`. Need to identify a minimum cutoff version and set it in `requirements-dev.txt`

**Comment by leewujung** [comment]
Related to datetime encoding: since we're going to refactor the package, let's pay some attention to xarray updates wrt pandas 2.0.0, and make sure we make necessary change once xarray is compatible with the latest version of pandas.

**Comment by ctuguinay** [comment]
Breaking changes due to datetime have been resolved.
