### ISSUE TITLE
Document current (May 2023) echoregions design

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echoregions#71]
We plan to refactor echoregions to streamline reading EVR and expand to writing EVR in summer 2023. Let's document the current echoregions design as the first step.

Related to #10 and #54

**Comment by ctuguinay** [comment]
[https://drive.google.com/file/d/1YK-t1VNL0lCeTVZhei9KGJlkMt0tw8xG/view?usp=drivesdk](https://drive.google.com/file/d/1YK-t1VNL0lCeTVZhei9KGJlkMt0tw8xG/view?usp=drivesdk)

Try this link. @leewujung
