### ISSUE TITLE
Store different labels to be layers in the mask dataset

### ISSUE THREAD

**Issue by valentina-s** [OSOceanAcoustics/echoregions#75]
On way to achieve that is through 3D array mask, or through stacking them as variables. One also generate them separately and stack the. `Regionmask` has the option [`mask_3D`](https://regionmask.readthedocs.io/en/stable/notebooks/mask_3D.html), which is binary.  One can also generate them by looping through the region types.

**Comment by ctuguinay** [comment]
Regions2D masking supports this now
