### ISSUE TITLE
Interpolation for Line Plot

### ISSUE THREAD

**Issue by ctuguinay** [OSOceanAcoustics/echoregions#82]
A possible feature could be using interpolation to connect some of these dots. More specifically, the interpolation algorithm would have to generate associated timestamp and depth values.

![line_plot](https://github.com/OSOceanAcoustics/echoregions/assets/87830138/f85562c0-eef5-4957-84d3-71ad385ab63c)

**Comment by valentina-s** [comment]
Yes, in fact interpolation is need to create a bottom mask aligned with the Sv data (the bottom grid is interpolated on the Sv time grid). See #43

**Comment by ctuguinay** [comment]
Potentially use the following interpolation scheme [https://github.com/uw-echospace/hake-labels/blob/2019/notebooks/examples/Bottom_for_x0022_2019.ipynb](https://github.com/uw-echospace/hake-labels/blob/2019/notebooks/examples/Bottom_for_x0022_2019.ipynb)
