### ISSUE TITLE
Provide an updated (converted with echopype 0.6.3) Sv files for the line plotting notebook

### ISSUE THREAD

**Issue by valentina-s** [OSOceanAcoustics/echoregions#84]
Make sure this notebook is up to date with the newer Sv format.

https://github.com/OSOceanAcoustics/echoregions/blob/main/notebooks/Lines_plotting.ipynb

**Comment by valentina-s** [comment]
@ctuguinay this dataset could be a more up to date choice for some of the examples:

https://drive.google.com/drive/u/0/folders/1XKtwlPDD7tAVPswf4GwoUVaKItgSa9K9

**Comment by leewujung** [comment]
These are the x22 evl and corresponding csv export: https://drive.google.com/drive/u/0/folders/10hZeD7YcSK02zNUedA9J1en7DKLXFw0r

**Comment by ctuguinay** [comment]
I added a converted file from `0.8.0`+ a while back. I used it in the recent notebook PR.
