### ISSUE TITLE
Add Type Checking

### ISSUE THREAD

**Issue by ctuguinay** [OSOceanAcoustics/echoregions#86]
As of right now, no form of type checking has been enforced in any of the echoregion modules. We will need type-checking as there exist some functions where it is unclear as to what type of parameters they let pass. For example, in the [lines plot function](https://github.com/OSOceanAcoustics/echoregions/blob/main/echoregions/plot/line_plot.py), passing in a string representing date will cause comparison errors (starting from Pandas 2.0) with a Timestamp object. Using [echopype](https://github.com/OSOceanAcoustics/echopype) as an example of implementing type checking, we will do the following:

- [ ] Implement type checking for all (applicable) functions in /convert, /formats, /mask, /plot.
- [ ] Implement type hints for all (applicable) functions in /convert, /formats, /mask, /plot.

**Comment by leewujung** [comment]
Please also include add type hints for the functions in this issue. See various echopype functions for example, like [here](https://github.com/OSOceanAcoustics/echopype/blob/dev/echopype/echodata/combine.py).
