### ISSUE TITLE
Determine multi-class region mask organization

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echoregions#87]
Currently our region mask handles a single class only, but we should generalize it to handle multi-class labels, since it is a common case and we'll likely run into that very soon.

**Comment by valentina-s** [comment]
Reference for creating 3D Regionmask: https://regionmask.readthedocs.io/en/stable/notebooks/mask_3D.html

**Comment by valentina-s** [comment]
Some other formats for storing multiclass labels:

* [COCO format](https://cocodataset.org/#home)

**Comment by leewujung** [comment]
We decided to first implement the 3D (`(label, depth, time)`) one-hot format first, and then we will deal with the case when some label classes overlap in the 2D (`(depth, time)`) format.

Related to #92.

**Comment by leewujung** [comment]
Hey @ctuguinay : The majority of this is addressed in #96, right? If I understand correctly, right now for the scenarios where the multi-class labels do not overlap at any pixels, the conversion between 3d and 2d formats are in place now. For the scenario where the multi-class labels do overlap, it seem the simplest is to only use the 3d format?

**Comment by leewujung** [comment]
Just re-read the above discussion on the case when one of the classes is missing -- it seems that we can stay with the handling right now (i.e. create whatever "slices" of classes that exist in the labels). We can think about this again once we get to more diverse labels and it may become obvious then which way we should go, since this is just an abstract question at the moment. So, I'll close this issue now!
